sudo: required
language: node_js
node_js: stable
script: bash ./deploy.sh
branches:
  only:
  - main
notifications:
  email: false

env:
  global:
  - secure: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDY3391o6MzQj1Rn2OEua6G53K8KlmbPxW3BnYsulOEmUIUY0Sj9a2uMjsTDS1kE+oayrvY9NPHTPWsEz3OXo7SZpUrNrP2Tx/U52pS1/NA9NYXKliKHKSSkrlTDDempHAhxJOULrYWjVwsHnLa3KyP2WLlEo6nUtlfawFWrUBSNL+ALgM+F2AaH7DY76sjzTlFMBpl/CjX/JBc9SajxgH/rvpIaC98avRnuazC08uY1g1ZBrTUS7WxiZXbmZA7kx+TIgtKmeLDYFPwNrytZQHe1i/3VLQGrPBiTgFbh7I5Zr2c8fqAAj9pMJOL9abSX9AlPbJ23SNNTVXKzLKLWhRGHLvl0dW/Fn2YoclNeOyThxjsgUx8b2EDJifjMt45Rz5K9gciMauy9OL+hDDsCTHfXOTOHcli5g8ONgztusVXhxuBbNRbiLG6785BB72rcijClx9zqxuNQ4Da9hy9R+Am3UQrKNiJ9y3PAiYhYRCRJi5xs8dGiVlB7HxNRCp0dmKTfIX25iBE6Tarc6UyfMVK6YexxHX2PbcraGUv99LguKVxRgZzkZpBulypO4UG6OQsu+dc5oIj3cR/0rL47pC4xjDJd92LVrmqIWkGN6JTTyQAVkEFAHxTfRyRAUJtUmvfK7NoHj+KPAKtgzHiSKbOhDqFcJSMtHDY2lbzRdZ8TQ== 16bd